ALTER TABLE clubs ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT;
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS stripe_subscription_id TEXT;
ALTER TABLE clubs ADD COLUMN IF NOT EXISTS subscription_ends_at TIMESTAMPTZ;
